name: lua_dardo
description: A Lua virtual machine written in Dart, which implements Lua5.3 version.
version: 0.0.5
homepage: https://github.com/arcticfox1919/LuaDardo.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  sprintf: ^7.0.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.25.8
